### ISSUE TITLE
BR server pls

### ISSUE THREAD

**Issue by Suburbanno** [DanyalS/LoL-Ping#1]

**Comment by DanyalS** [comment]
I added the BR server just now. You can check and let me know if its working correctly!

**Comment by Suburbanno** [comment]
@DanyalS Apparently not working, my ping is 79ms ...
But in your fact Checker shows, min 308ms ...
![screenshot_2](https://cloud.githubusercontent.com/assets/13632826/23089351/be46c048-f56e-11e6-9262-0ffaa42bbf91.png)
